---
owner: minhh2792
repo: uptime
sites:
  - name: "[MineVN Studio] License server"
    url: https://license.minevn.net/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://minevn.studio/img/minevn-studio-avatar.png
  - name: "[MineVN] Minecraft"
    check: tcp-ping
    url: mc.minevn.net
    maxResponseTime: 10000
    port: 25565
    icon: https://i.imgur.com/OGV4Bar.png
  - name: "[MineVN] Maven repo & resource pack server"
    url: https://pack.minevn.net
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://i.imgur.com/OGV4Bar.png
  - name: "[MineVN] Website"
    url: https://minevn.net
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://i.imgur.com/OGV4Bar.png
  - name: "[MineVN] Minetrack"
    url: https://track.minevn.net
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://raw.githubusercontent.com/Cryptkeeper/Minetrack/main/assets/images/logo.svg
  - name: "[MineVN] Grafana"
    url: https://grafana.minevn.net
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://grafana.com/static/assets/img/fav32.png
status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  favicon: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: night
  name: Uptime Monitor
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: https://minhh2792.github.io/uptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
