# Change these first
owner: minhh2792 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: MineVN Network
    check: "tcp-ping"
    url: minevn.net
    port: 25565
  - name: MineVN Maven & Resource pack
    url: http://app.minevn.net/pack
  - name: MineVN Website
    url: http://minevn.net
  - name: Kiwi AdguardHome server
    url: https://minhh2792.me
  - name: Kiwi Debian server
    url: $SERVER_IP
    

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor
  introTitle: "Kiwi's personal uptime monitor."
  introMessage: [**Powered by Upptime**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
