owner: minhh2792
repo: uptime

sites:
  - name: MineVN Network
    check: "tcp-ping"
    url: minevn.net
    maxResponseTime: 5000
    port: 25565
    icon: https://i.imgur.com/OGV4Bar.png
  - name: MineVN Maven & Resource pack
    url: http://app.minevn.net/pack
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://i.imgur.com/OGV4Bar.png
  - name: MineVN Website
    url: http://minevn.net
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://i.imgur.com/OGV4Bar.png
  - name: Pterodactyl 
    url: $PANEL_URL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
    icon: https://i.imgur.com/WYyj7ut.png
  - name: AdguardHome server
    check: "tcp-ping"
    url: $SERVER_IP
    maxResponseTime: 5000
    port: 53
    expectedStatusCodes:
      - 200
      - 201
      - 404
    icon: https://i.imgur.com/pRa8pFr.png
  - name: Debian server
    url: $SERVER_IP
    maxResponseTime: 5000
    icon: https://i.imgur.com/HDEi4j5.png

status-website:
  baseUrl: /uptime
  logoUrl: "https://i.imgur.com/jvCuSsD.png"
  favicon: https://i.imgur.com/jvCuSsD.png
  theme: night
  name: Uptime Monitor
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: https://minhh2792.github.io/uptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
