owner: minhh2792
repo: uptime

sites:
  - name: MineVN Network
    check: "tcp-ping"
    url: minevn.net
    port: 25565
    maxResponseTime: 5000
  - name: MineVN Maven & Resource pack
    url: http://app.minevn.net/pack
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: MineVN Website
    url: http://minevn.net
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Kiwi AdguardHome server
    url: https://minhh2792.me
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Kiwi Debian server
    url: $SERVER_IP
    maxResponseTime: 5000

status-website:
  baseUrl: /uptime
  logoUrl: ''
  favicon: https://i.imgur.com/iiyljA2.jpg
  theme: dark
  name: Uptime Monitor
  introTitle: "Kiwi personal uptime monitor."
  introMessage: "> Updated every 5 mins"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
